-- 코드를 입력하세요
SELECT FIRST_HALF.FLAVOR FROM FIRST_HALF
    JOIN ICECREAM_INFO ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
    WHERE FIRST_HALF.TOTAL_ORDER>3000 
    AND LEFT(ICECREAM_INFO.INGREDIENT_TYPE,5) = 'fruit'
    ORDER BY TOTAL_ORDER DESC;